### ISSUE TITLE
Not working with GL version 3.x

### ISSUE THREAD

**Issue by frauzufall** [armadillu/ofxFontStash2#5]
Hi,

I just discovered this addon and it is wonderul, thank you!

The only issue I have right now is that I can't use it in a program that is initialized using openGL version 3.2. which seems to be required by ofNode.
```
ofGLFWWindowSettings settings;
	settings.setGLVersion(3, 2);
	settings.width = 1280;
	settings.height = 720;
	ofCreateWindow(settings);
```
With this code in main.cpp, the text does not show up. If I comment out the line about the version or if I set it to 2.1 for example, it works again. Do you have an idea what is going wrong or a hint what I could do?
Cheers, Deborah

**Comment by frauzufall** [comment]
Ah sorry I just saw the note about it on the README! Will look into that.

**Comment by armadillu** [comment]
GL3 support is very rough still - also I don't think ofNode needs GL3. Unless you are doing custom shaders or more advanced things there's little reason to do GL3. The whole add-on is still very rough.
ofxFontStash has an uglier API but offers more features than this if you can stick to GL2

**Comment by frauzufall** [comment]
Yes I just figured out that ofNode works with GL2 as well :) No need for GL3. 

I tried ofxFontStash by integrating it into ofxGuiExtended (https://github.com/frauzufall/ofxGuiExtended/tree/fontstash) but the font looked super fuzzy (small font sizes, linux). I switched to ofxFontStash2 (not yet online) and it looks way better. The only thing that is not working for me is `getTextBounds()`. 
(It's pretty hacky because I have a font object for every gui object instead of a global one but I just wanted to try it out first)

**Comment by armadillu** [comment]
I see! ofxFonstash is much better at getting rect sizes (also for paragraphs), and also has proper DPI support (so you render fonts upscaled). Fuzzy fonts usually happen bc you are drawing on a non even pixel (i.e. drawing at vec(10.5, 10.5) instead of on an integer position (10,0). It's also pretty fast, and allows mipmaps... Also ofxFontstash2 will likely change api often.

**Comment by frauzufall** [comment]
Alright, I will try again if I get it to work with ofxFontStash.

The reason I was integrating it initially though was because of the subpixel font rendering. The standard OF font options can't do that and I have animated panels where the font moved very shaky because of that. I'll find a way!

Thanks again!

**Comment by armadillu** [comment]
I think Pango is the only way to do SubPixel font rendering. FontStash (and all the other atlas-based font systems) won't give you super good quality bc the letters are only rendered once. Mango will layout each letter in a subpixel fashion, giving you better kerning looks overall. It's just a real pain to setup a project to us eat though (and that is if you can find precompiled libs that work on your platform)

**Comment by armadillu** [comment]
This is a pretty good starting point for that https://github.com/kitschpatrol/ofxPango

**Comment by frauzufall** [comment]
I'll check that out! But probably try to get the best quality with ofxFontStash (I also wanted to try integrating ofxFontAwesome for panel headers and individual buttons etc.). It doesn't have to be perfectly sharp, but the shivering letters of ofTrueTypeFont and ofBitmapFont when animating a panel were disturbing.
